### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [thundermiracle/react-sunflower#1]
Greetings, I just made a logo for your project, hope you like it.

![react-sunf1](https://user-images.githubusercontent.com/35619342/40274147-a2685b16-5b9d-11e8-922d-1c0425296341.png)
![react-sunf2](https://user-images.githubusercontent.com/35619342/40274148-a2c250f8-5b9d-11e8-9306-9439ec28a9b5.png)
![react-sunfbw](https://user-images.githubusercontent.com/35619342/40274146-a199b720-5b9d-11e8-855c-32d1910f9436.png)
If you liked it, let me know which color variation and I'll upload the files on a pull request.
Also please let me know if you want me to add/modify something.

**Comment by thundermiracle** [comment]
Thank you for your proprosal!
I wasn't even aware that this project can attract a issue.

I like the green one. It looks like real sunflower.
Feel free to PR.

**Comment by michaelizer** [comment]
Done ([#2](https://github.com/thundermiracle/react-sunflower/pull/2)). It was a pleasure sir :)

**Comment by thundermiracle** [comment]
It looks great! Thank you very much!
I think I'll use your great work as site's icon later.
